### ISSUE TITLE
[feat] 프로젝트 코드 구조 재편성

### ISSUE THREAD

**Issue by w00shh** [billimiut/billimiut_backend#7]
## 📌  Issue
현재 프로젝트의 디렉토리 구조를 개선하고, 코드의 유지보수성과 확장성을 높이기 위해 모듈화를 진행합니다.

## ✅  To-do

- [x] 디렉토리 구조 재편성
- [x] 유저 관리 api 작성
- [x] 게시글 관리 api 작성
- [x] 이미지 업로드 api 작성
- [x] 채팅 api 작성
- [x] 이전 api와 연동
